### ISSUE TITLE
speaker sample

### ISSUE THREAD

**Issue by mhama** [sipeed/MaixPy_scripts#2]
It would be better to have some samples to use the speaker, as Maix Go have a good-looking speaker hardware.

**Comment by Neutree** [comment]
https://github.com/sipeed/MaixPy_scripts/blob/master/multimedia/audio/play_wav.py

**Comment by linycm** [comment]
I test play_wav.py and got the below error. Pls advise. thanks!

wav_info = player.play_process(wav_dev)

[MAIXPY]: wav error code : 7
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: wav init error

And for player.volume(40), I got error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'AUDIO' object has no attribute 'volume'

**Comment by Neutree** [comment]
@linycm wait for the new release or build yourself firmware

**Comment by linycm** [comment]
@Neutree I build firmware again but still got error when
wav_info = player.play_process(wav_dev)
[MAIXPY]: wav error code : 7
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: wav init error
--------
core dump: fault store
Cause 0x0000000000000007, EPC 0x00000000800c2a44
.......

**Comment by Neutree** [comment]
@linycm The header of wav file you used have some problem, please send me your wav file, so I can checke the header, or just convert to wav file maixpy support. [here](https://cloudconvert.com/mp3-to-wav) for example

**Comment by linycm** [comment]
[radio.wav.tar.gz](https://github.com/sipeed/MaixPy_scripts/files/3202723/radio.wav.tar.gz)

@Neutree pls help to check. thanks!

**Comment by Neutree** [comment]
@linycm This audio file uses ADPCM encoding. MaixPy only supports PCM 16bit little endian encoding. Please find a way to convert to such a format. There is no plan to support ADPCM.

![image](https://user-images.githubusercontent.com/8625829/58141243-47da0880-7c75-11e9-800b-fc57cc57fd64.png)

MaixPy support like this one:

![image](https://user-images.githubusercontent.com/8625829/58141257-51637080-7c75-11e9-980b-f1db458b2b4c.png)
