### ISSUE TITLE
Self_learning_classifier - ERR_KMODEL_VERSION

### ISSUE THREAD

**Issue by mat-lo** [sipeed/MaixPy_scripts#46]
Hi, 

I'm following the instructions here:
https://github.com/sipeed/MaixPy_scripts/blob/master/machine_vision/doc/self_learning_classifier.md

But when I run the [demo script](https://github.com/sipeed/MaixPy_scripts/blob/master/machine_vision/self_learning_classifier.py) I get this error:

```
[MAIXPY]: find ov2640
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "<stdin>", line 2, in <module>
  File "<string>", line 49, in <module>
ValueError: [MAIXPY]kpu: load error:2002, ERR_KMODEL_VERSION: only support kmodel V3/V4 now
``` 

I downloaded the .smodel using the Keygen, and uploaded using kflash.
I'm not sure about the address where to load the downloaded .smodel

**Comment by easy-and-simple** [comment]
Hi
I think that if you insert this line
time.sleep_ms(500)
between line 61 and 62 of self_learning_classifier.py it will start working
